import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Zap, Globe, DollarSign, Users, Sparkles, Check, ArrowRight, Code, TrendingUp } from 'lucide-react';

export default function Home() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<'business' | 'developer'>('business');

  const businessFeatures = [
    { icon: Sparkles, title: 'AI-Powered Design', description: 'Just chat with our AI - no design skills needed' },
    { icon: Globe, title: 'Instant Hosting', description: 'Your site goes live on your custom domain instantly' },
    { icon: Zap, title: 'Lightning Fast', description: 'Get a professional website in minutes, not weeks' },
    { icon: DollarSign, title: 'All-in-One Platform', description: 'Website, hosting, domain, analytics - everything included' }
  ];

  const developerFeatures = [
    { icon: Code, title: 'Instant Portfolio', description: 'Get 10 stunning demo websites generated by AI' },
    { icon: Users, title: 'Client Management', description: 'Dashboard to manage all your clients in one place' },
    { icon: TrendingUp, title: 'B2B2C Model', description: 'Get clients, we build - you take the credit & revenue' },
    { icon: Globe, title: 'White Label', description: 'Your brand, your clients, powered by our AI' }
  ];

  const plans = [
    {
      name: 'Personal',
      price: 29,
      description: 'For individuals and small projects',
      features: [
        '10 websites',
        'Custom domains',
        '50 AI generations/month',
        'Advanced analytics',
        '10GB storage'
      ],
      cta: 'Start Free Trial',
      popular: false
    },
    {
      name: 'Freelancer',
      price: 99,
      description: 'For professional freelancers',
      features: [
        '50 websites',
        '20 clients',
        '200 AI generations/month',
        'AI-generated portfolio',
        'White-label branding',
        'Client management',
        'Priority support'
      ],
      cta: 'Start Building',
      popular: true
    },
    {
      name: 'Agency',
      price: 299,
      description: 'For agencies and teams',
      features: [
        'Unlimited websites',
        'Unlimited clients',
        '1000 AI generations/month',
        'AI portfolio generator',
        'Full white-label',
        'Team collaboration (10)',
        'API access',
        'Dedicated support'
      ],
      cta: 'Go Enterprise',
      popular: false
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-indigo-50">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-lg border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <div className="flex items-center space-x-2">
              <Sparkles className="w-8 h-8 text-indigo-600" />
              <span className="text-2xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                WebChat.ai
              </span>
            </div>
            <div className="hidden md:flex space-x-8">
              <a href="#features" className="text-gray-600 hover:text-indigo-600 transition">Features</a>
              <a href="#pricing" className="text-gray-600 hover:text-indigo-600 transition">Pricing</a>
              <a href="#how-it-works" className="text-gray-600 hover:text-indigo-600 transition">How It Works</a>
            </div>
            <div className="flex space-x-4">
              <button
                onClick={() => navigate('/login')}
                className="px-4 py-2 text-gray-700 hover:text-indigo-600 transition"
              >
                Login
              </button>
              <button
                onClick={() => navigate('/register')}
                className="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition shadow-lg shadow-indigo-200"
              >
                Get Started
              </button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-4">
        <div className="max-w-7xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h1 className="text-6xl md:text-7xl font-bold mb-6 leading-tight">
              Build Stunning Websites
              <br />
              <span className="bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 bg-clip-text text-transparent">
                Just by Chatting with AI
              </span>
            </h1>
            <p className="text-xl md:text-2xl text-gray-600 mb-12 max-w-3xl mx-auto">
              No templates. No coding. No hassle.
              Whether you're a business owner or a web developer, we've got you covered.
            </p>

            {/* Tab Switcher */}
            <div className="inline-flex rounded-xl bg-white p-1 shadow-lg mb-12">
              <button
                onClick={() => setActiveTab('business')}
                className={`px-8 py-3 rounded-lg font-medium transition ${
                  activeTab === 'business'
                    ? 'bg-indigo-600 text-white shadow-md'
                    : 'text-gray-600 hover:text-indigo-600'
                }`}
              >
                For Business Owners
              </button>
              <button
                onClick={() => setActiveTab('developer')}
                className={`px-8 py-3 rounded-lg font-medium transition ${
                  activeTab === 'developer'
                    ? 'bg-indigo-600 text-white shadow-md'
                    : 'text-gray-600 hover:text-indigo-600'
                }`}
              >
                For Developers
              </button>
            </div>

            <div className="flex justify-center gap-4 mb-16">
              <button
                onClick={() => navigate('/register')}
                className="px-8 py-4 bg-indigo-600 text-white text-lg rounded-xl hover:bg-indigo-700 transition shadow-xl shadow-indigo-200 flex items-center gap-2"
              >
                Start Building for Free
                <ArrowRight className="w-5 h-5" />
              </button>
              <button
                onClick={() => navigate('/builder')}
                className="px-8 py-4 bg-white text-indigo-600 text-lg rounded-xl hover:bg-gray-50 transition shadow-xl border-2 border-indigo-600"
              >
                Try Demo
              </button>
            </div>
          </motion.div>

          {/* Demo Preview */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="max-w-5xl mx-auto"
          >
            <div className="bg-white rounded-2xl shadow-2xl overflow-hidden border border-gray-200">
              <div className="bg-gradient-to-r from-indigo-600 to-purple-600 p-3 flex items-center space-x-2">
                <div className="flex space-x-2">
                  <div className="w-3 h-3 rounded-full bg-red-400"></div>
                  <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
                  <div className="w-3 h-3 rounded-full bg-green-400"></div>
                </div>
                <div className="flex-1 text-center text-white text-sm font-medium">
                  Chat with AI ’ Beautiful Website
                </div>
              </div>
              <div className="aspect-video bg-gradient-to-br from-indigo-50 to-purple-50 flex items-center justify-center">
                <div className="text-center p-8">
                  <Sparkles className="w-20 h-20 text-indigo-600 mx-auto mb-4" />
                  <p className="text-xl text-gray-600 font-medium">Live demo coming soon!</p>
                  <p className="text-gray-500 mt-2">See the AI build a website in real-time</p>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4">
          <h2 className="text-4xl md:text-5xl font-bold text-center mb-16">
            {activeTab === 'business' ? 'Everything You Need' : 'Power Your Agency with AI'}
          </h2>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {(activeTab === 'business' ? businessFeatures : developerFeatures).map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="p-6 bg-gradient-to-br from-indigo-50 to-purple-50 rounded-xl hover:shadow-xl transition"
              >
                <feature.icon className="w-12 h-12 text-indigo-600 mb-4" />
                <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="py-20 bg-gradient-to-br from-gray-50 to-indigo-50">
        <div className="max-w-7xl mx-auto px-4">
          <h2 className="text-4xl md:text-5xl font-bold text-center mb-16">How It Works</h2>

          <div className="grid md:grid-cols-3 gap-12">
            {[
              { step: '1', title: 'Chat with AI', description: 'Tell our AI what you want. Just type like you\'re texting a friend.' },
              { step: '2', title: 'AI Builds Your Site', description: 'Watch as beautiful, professional website is generated in real-time.' },
              { step: '3', title: 'Go Live Instantly', description: 'Deploy to your custom domain with one click. That\'s it!' }
            ].map((item, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5, delay: index * 0.2 }}
                viewport={{ once: true }}
                className="text-center"
              >
                <div className="w-20 h-20 bg-indigo-600 text-white text-3xl font-bold rounded-full flex items-center justify-center mx-auto mb-6 shadow-xl">
                  {item.step}
                </div>
                <h3 className="text-2xl font-bold mb-4">{item.title}</h3>
                <p className="text-gray-600 text-lg">{item.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4">
          <h2 className="text-4xl md:text-5xl font-bold text-center mb-4">Simple, Transparent Pricing</h2>
          <p className="text-xl text-gray-600 text-center mb-16">Choose the plan that fits your needs</p>

          <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {plans.map((plan, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className={`relative p-8 rounded-2xl ${
                  plan.popular
                    ? 'bg-gradient-to-br from-indigo-600 to-purple-600 text-white shadow-2xl scale-105'
                    : 'bg-white border-2 border-gray-200'
                }`}
              >
                {plan.popular && (
                  <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-yellow-400 text-indigo-900 px-4 py-1 rounded-full text-sm font-bold">
                    MOST POPULAR
                  </div>
                )}
                <h3 className="text-2xl font-bold mb-2">{plan.name}</h3>
                <p className={`mb-6 ${plan.popular ? 'text-indigo-100' : 'text-gray-600'}`}>
                  {plan.description}
                </p>
                <div className="mb-6">
                  <span className="text-5xl font-bold">${plan.price}</span>
                  <span className={plan.popular ? 'text-indigo-100' : 'text-gray-600'}>/month</span>
                </div>
                <ul className="space-y-3 mb-8">
                  {plan.features.map((feature, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <Check className={`w-5 h-5 mt-0.5 flex-shrink-0 ${plan.popular ? 'text-white' : 'text-indigo-600'}`} />
                      <span className={plan.popular ? 'text-indigo-50' : 'text-gray-700'}>{feature}</span>
                    </li>
                  ))}
                </ul>
                <button
                  onClick={() => navigate('/register')}
                  className={`w-full py-3 rounded-lg font-semibold transition ${
                    plan.popular
                      ? 'bg-white text-indigo-600 hover:bg-gray-100'
                      : 'bg-indigo-600 text-white hover:bg-indigo-700'
                  }`}
                >
                  {plan.cta}
                </button>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-indigo-600 to-purple-600">
        <div className="max-w-4xl mx-auto text-center px-4">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
            Ready to Build Your Dream Website?
          </h2>
          <p className="text-xl text-indigo-100 mb-12">
            Join thousands of businesses and developers already using WebChat.ai
          </p>
          <button
            onClick={() => navigate('/register')}
            className="px-12 py-4 bg-white text-indigo-600 text-xl rounded-xl hover:bg-gray-100 transition shadow-2xl font-semibold inline-flex items-center gap-3"
          >
            Start Building for Free
            <ArrowRight className="w-6 h-6" />
          </button>
          <p className="text-indigo-200 mt-6">No credit card required " 14-day free trial</p>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-300 py-12">
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid md:grid-cols-4 gap-8 mb-8">
            <div>
              <div className="flex items-center space-x-2 mb-4">
                <Sparkles className="w-6 h-6 text-indigo-400" />
                <span className="text-xl font-bold text-white">WebChat.ai</span>
              </div>
              <p className="text-sm">The AI-powered website builder that just works.</p>
            </div>
            <div>
              <h4 className="font-bold text-white mb-4">Product</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#features" className="hover:text-white transition">Features</a></li>
                <li><a href="#pricing" className="hover:text-white transition">Pricing</a></li>
                <li><a href="#" className="hover:text-white transition">Templates</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold text-white mb-4">Company</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#" className="hover:text-white transition">About</a></li>
                <li><a href="#" className="hover:text-white transition">Blog</a></li>
                <li><a href="#" className="hover:text-white transition">Careers</a></li>
              </ul>
            </div>
            <div>
              <h4 className="font-bold text-white mb-4">Legal</h4>
              <ul className="space-y-2 text-sm">
                <li><a href="#" className="hover:text-white transition">Privacy</a></li>
                <li><a href="#" className="hover:text-white transition">Terms</a></li>
                <li><a href="#" className="hover:text-white transition">Security</a></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 pt-8 text-center text-sm">
            <p>&copy; 2025 WebChat.ai. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
