export const sampleWebsite = {
  html: `
    <div class="hero">
      <h1>Welcome to My Website</h1>
      <p>This is a sample website generated by AI</p>
      <button class="cta-button">Get Started</button>
    </div>
  `,
  css: `
    body {
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .hero {
      text-align: center;
      color: white;
      padding: 2rem;
    }

    h1 {
      font-size: 3rem;
      margin-bottom: 1rem;
    }

    p {
      font-size: 1.25rem;
      margin-bottom: 2rem;
      opacity: 0.9;
    }

    .cta-button {
      background: white;
      color: #667eea;
      border: none;
      padding: 1rem 2rem;
      font-size: 1rem;
      font-weight: 600;
      border-radius: 0.5rem;
      cursor: pointer;
      transition: transform 0.2s;
    }

    .cta-button:hover {
      transform: scale(1.05);
    }
  `,
  js: `
    document.querySelector('.cta-button').addEventListener('click', () => {
      alert('Button clicked!');
    });
  `
};
